## Arithmetic Operations with <span style="color: green;">array</span>s  and  Individual Numeric Values
First, let’s perform element-wise arithmetic with arrays and numeric values by using arithmetic operators and augmented assignments. Element-wise operations are applied to every element, so snippets below multiplies every element by 2 and then cubes every element. Each returns a new array containing the result:

In [2]:
import numpy as np 
numbers = np.arange(1, 6) 
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers * 2  

array([ 2,  4,  6,  8, 10])

In [4]:
numbers ** 3  

array([  1,   8,  27,  64, 125])

In [5]:
numbers # numbers is unchanged by the arithmetic operators 

array([1, 2, 3, 4, 5])

Augmented assignments modify every element in the left operand.

In [7]:
numbers += 5
numbers

array([11, 12, 13, 14, 15])

## Broadcasting 
Normally, the arithmetic operations require as operands two arrays of the same size and shape. When one operand is a single value, called a scalar, NumPy performs the element-wise calculations as if the scalar were an array of the same shape as the other operand, but with the scalar value in all its elements. This is called broadcasting. Snippets [3], [4] and [7] each use this capability. For example, snippet [3] is equivalent to: numbers * [2, 2, 2, 2, 2]

## Arithmetic Operations Between arrays 
You may perform arithmetic operations and augmented assignments between arrays of the same shape. Let’s multiply the one-dimensional <span style="color: red;">array </span>s <span style="color: red;">numbers </span> and <span style="color: red;">numbers2 </span> (created below) that each contain five elements:

In [12]:
numbers = np.arange(1, 6)
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers2 = np.linspace(1.1, 5.5, 5) 
numbers2 

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [14]:
numbers * numbers2 

array([ 1.1,  4.4,  9.9, 17.6, 27.5])

The result is a new array formed by multiplying the arrays element-wise in each operand—11 * 1.1, 12 * 2.2, 13 * 3.3, etc. Arithmetic between arrays of integers and floating-point numbers results in an array of floating-point numbers.

## Comparing arrays 
We can compare arrays with individual values and with other arrays. Comparisons are performed element-wise. Such comparisons produce arrays of Boolean values in which each element’s True or False value indicates the comparison result:

In [15]:
numbers 

array([1, 2, 3, 4, 5])

In [16]:
numbers >= 13  

array([False, False, False, False, False])

In [17]:
numbers2  

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [18]:
numbers2 < numbers 

array([False, False, False, False, False])

In [19]:
numbers==numbers

array([ True,  True,  True,  True,  True])