## NumPy's n-dimensional array 
Python presents native data structures, such as lists and dictionaries, which you should use to the best of your ability. Lists, for example, can store sequentially heterogeneous objects (for instance, you can save numbers, texts, images, and sounds in the same list). On the other hand, dictionaries can recall content. The content can be any Python object, and often it is a list of another dictionary. Thus, dictionaries allow you to access complex, multidimensional data structures.<br>

Anyway, lists and dictionaries have their own limitations, such as the following: 
+ There's the problem with memory and speed. They are not really optimized for using nearly contiguous chunks of memory, and this may become a problem when trying to apply highly optimized algorithms or multiprocessor computations, because memory handling may turn into a bottleneck. 
+ They are excellent for storing data but not for operating on it. Therefore, whatever you may want to do with your data, you have to first define custom functions and iterate or map over the list or dictionary elements. Iterating may often prove suboptimal when working on a large amount of data. 

NumPy offers a *ndarray* object class (n-dimensional array) that has the following attributes: 
+ It is memory optimal (and, besides other aspects, configured to transmit data to C or Fortran routines in the best-performing layout of memory blocks) 
+ It allows for fast linear algebra computations (vectorization) and element-wise operations (broadcasting) without any need to use iterations with for loops 
+ Critical libraries, such as SciPy or Scikit-learn, expect arrays as an input for their functions to operate correctly 

All of this comes with some limitations. In fact, ndarray objects have the following drawbacks: 
+ They usually store only elements of a single, specific data type, which you can define beforehand (but there's a way to define complex data and heterogeneous data types, though they could be very difficult to handle for analysis purposes). 
+ After they are initialized, their size is fixed. If you want to change their shape, you have to create them anew.

# Creating *arrays* from Existing Data

To get an access to the functions in *NumPy* Library, we first need to import it. The *NumPy* documentation recommends importing the numpy module as *np* so that you can access its members with "np.": 

In [50]:
import numpy as np

The <span style="color: green;">numpy</span>  module provides various functions for creating <span style="color: green;">arrays</span> .<br>
Here we use the <span style="color: green;">array</span>  function, which receives as an argument an array or other collection of elements and returns a new array containing the argument’s elements.<br>


In [51]:
print('Creating an array from a list')
numbers1 = np.array([7, 8, 9, 10, 11])
print(numbers1)

Creating an array from a list
[ 7  8  9 10 11]


## Multidimensional Arguments 

The array function copies its argument’s dimensions.<br> Let’s create an array from a two-row-by-three-column list:

In [52]:
np.array([[1, 2, 3], [4, 5, 6]]) 

array([[1, 2, 3],
       [4, 5, 6]])

NumPy auto-formats arrays, based on their number of dimensions, aligning the columns within each row.

## Determining an array’s Element Type 

The *array* function determines an array’s element type from its argument’s elements. You can check the element type with an array’s *dtype* attribute:

In [53]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(floats.dtype)
print(floats)

float64
[0.  0.1 0.2 0.3 0.4]


In [54]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
print(integers.dtype)
print(integers)

int64
[[1 2 3]
 [4 5 6]]


As you’ll see in the coming sections, various array-creation functions receive a dtype keyword argument so you can specify an array’s element type. For performance reasons, NumPy is written in the C programming language and uses C’s data types. By default, NumPy stores integers as the NumPy type int64 values—which correspond to 64-bit (8-byte) integers in C—and stores floating-point numbers as the NumPy type float64 values—which correspond to 64-bit (8-byte) floating-point values in C. In our examples, most commonly you’ll see the types int64, float64, bool (for Boolean) and object for non-numeric data (such as strings). The complete list of supported types is at https://docs.scipy.org/doc/numpy/user/basics.types.html.

## Determining an array’s Dimensions 
The attribute <span style="color: green;">ndim</span> contains an array’s number of dimensions and the attribute <span style="color: green;">shape</span> contains a tuple specifying an array’s dimensions:

In [55]:
integers.ndim 

2

In [56]:
 floats.ndim 

1

In [57]:
integers.shape 

(2, 3)

In [58]:
floats.shape

(5,)

Here, integers has 2 rows and 3 columns (6 elements) and floats is one-dimensional, so snippet above shows a one-element tuple (indicated by the comma) containing floats’ number of elements (5).

## Determining an array’s Number of Elements 
You can view an array’s total number of elements with the attribute *size*:

In [59]:
integers.size

6

Note that integers’ size is the product of the shape tuple’s values—two rows of three elements each for a total of six elements.

## Filling arrays with Specific Values 

**NumPy** provides functions <span style="color: green;">zeros, ones</span>  and  <span style="color: green;">full</span> for creating arrays containing <span style="color: green;">0s, 1s or a specified value</span>, respectively. By default, zeros and ones create arrays containing float64 values. The first argument to these functions must be an integer or a tuple of integers specifying the desired dimensions. For an integer, each function returns a one-dimensional array with the specified number of elements:

In [60]:
import numpy as np 
np.zeros(6) 

array([0., 0., 0., 0., 0., 0.])

For a tuple of integers, these functions return a multidimensional array with the specified dimensions. You can specify the array’s element type with the zeros and ones function’s *dtyp*e keyword argument:

In [61]:
np.ones((2, 4), dtype=int) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

The array returned by *full* contains elements with the second argument’s value and type:

In [62]:
np.full((4, 5), 9.6 ,dtype=float)

array([[9.6, 9.6, 9.6, 9.6, 9.6],
       [9.6, 9.6, 9.6, 9.6, 9.6],
       [9.6, 9.6, 9.6, 9.6, 9.6],
       [9.6, 9.6, 9.6, 9.6, 9.6]])

## Creating arrays from Ranges 
*NumPy* provides optimized functions for creating arrays from ranges. We focus on simple evenly spaced integer and floating-point ranges, but NumPy also supports nonlinear ranges. https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html.

## Creating Integer Ranges with <span style="color: green;">arange</span> 

Let’s use *NumPy*’s <span style="color: green;">arange</span>  function to create integer ranges—similar to using built-in function <span style="color: green;">range</span>. <br>
In each case, <span style="color: green;">arange</span> first determines the resulting array’s number of elements, allocates the memory, then stores the specified range of values in the array:

In [63]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [64]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [65]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

## Creating Floating-Point Ranges with <span style="color: green;">linspace</span>  
You can produce evenly spaced floating-point ranges with NumPy’s <span style="color: green;">linspace</span> function. The function’s first two arguments specify the starting and ending values in the range, and **the ending value is included in the array**. The optional keyword argument num specifies the number of evenly spaced values to produce—this argument’s default value is 50:

In [66]:
#num is not specified ,default is 50,linspace
#divides the interval (0.0,1.0) into 50 equally 
#spaced grids
np.linspace(0.0, 1.0)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [67]:
#num is specified as 5 ,linspace
#divides the interval (0.0,1.0) into 5 equally 
#spaced grids
np.linspace(0.0, 1.0,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Reshaping an array 
You also can create an array from a range of elements, then use array method <span style="color: green;">reshape</span>   to transform the one-dimensional array into a multidimensional array.<br>
Let’s create an array containing the values from 1 through 20, then reshape it into four rows by five columns:

In [68]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Note the *chained method calls* in the preceding snippet. First, <span style="color: green;">arange</span> produces an array containing the values 1–20. Then we call <span style="color: green;">reshape</span> on that array to get the 4-by-5 array that was displayed. You can reshape any array, provided that the new shape has the same number of elements as the original. So a six-element one-dimensional array can become a 3-by-2 or 2-by-3 array, and vice versa, but attempting to reshape a 15-element array into a 4-by-4 array (16 elements) causes a ValueError.
