## Reshaping and Transposing 
We’ve used  <span style="color: green;">array</span> method <span style="color: green;">reshape</span>  to produce two-dimensional arrays from one-dimensional ranges. NumPy provides various other ways to reshape arrays. 

### reshape vs. resize 

The array methods <span style="color: green;">reshape</span> and <span style="color: green;">resize</span> both enable you to change an array’s dimensions. Method <span style="color: green;">reshape</span> returns a view (shallow copy) of the original array with the new dimensions. It does not modify the original array:

In [1]:
import numpy as np 
grades = np.array([[87, 96, 70], [100, 87, 90]]) 
grades 

array([[ 87,  96,  70],
       [100,  87,  90]])

In [2]:
grades.reshape(1, 6) 

array([[ 87,  96,  70, 100,  87,  90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Method <span style="color: green;">resize</span> modifies the original array’s shape:

In [4]:
grades.resize(1, 6)
grades

array([[ 87,  96,  70, 100,  87,  90]])

## flatten vs. ravel

You can take a multidimensional array and flatten it into a single dimension with the methods flatten and ravel. Method <span style="color: green;">flatten </span> deep copies the original array’s data:

In [5]:
grades = np.array([[87, 96, 70], [100, 87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [8]:
flatten=grades.flatten()
flatten

array([ 87,  96,  70, 100,  87,  90])

In [9]:
grades 

array([[ 87,  96,  70],
       [100,  87,  90]])

To confirm that <span style="color: green;">grades</span> and <span style="color: green;">flattened</span>  do not share the data, let’s modify an element of <span style="color: green;">flattened</span> , then display both arrays:

In [10]:
flatten[0]=0

flatten

array([  0,  96,  70, 100,  87,  90])

In [11]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

Method <span style="color: green;">ravel</span>  produces a view of the original array, which shares the grades array’s data:

In [12]:
raveled=grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [13]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [14]:
raveled[0]=3
raveled

array([  3,  96,  70, 100,  87,  90])

In [15]:
grades

array([[  3,  96,  70],
       [100,  87,  90]])

## Transposing Rows and Columns 
You can quickly transpose an array’s rows and columns—that is “flip” the array, so the rows become the columns and the columns become the rows. The <span style="color: red;">T</span> **attribute** returns a transposed view (shallow copy) of the array. The original grades array represents two students’ grades (the rows) on three exams (the columns).<br> Let’s transpose the rows and columns to view the data as the grades on three exams (the rows) for two students (the columns):

In [18]:
grades.T

array([[  3, 100],
       [ 96,  87],
       [ 70,  90]])

Transposing does not modify the original array:

In [17]:
grades

array([[  3,  96,  70],
       [100,  87,  90]])

## Horizontal and Vertical Stacking 
You can combine arrays by adding more columns or more rows—known as horizontal stacking and vertical stacking. Let’s create two 2-by-3 array of grades:

In [19]:
grades1=np.array([[60,45,67],[90,78,98]])
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

We can combine grades1 and grades2 with NumPy’s **hstack** (horizontal stack) function by passing a tuple containing the arrays to combine. The extra parentheses are required because **hstack** expects one argument:

In [20]:
np.hstack((grades1, grades2))

array([[ 60,  45,  67,  94,  77,  90],
       [ 90,  78,  98, 100,  81,  82]])

we can also combine grades1 and grades2 with NumPy’s **vstack** (vertical stack) function:

In [21]:
np.vstack((grades1, grades2))

array([[ 60,  45,  67],
       [ 90,  78,  98],
       [ 94,  77,  90],
       [100,  81,  82]])